// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StockExchangeSystem.Data;

#nullable disable

namespace StockExchangeSystem.Data.Migrations
{
    [DbContext(typeof(StockExchangeDbContext))]
    partial class StockExchangeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.16");

            modelBuilder.Entity("StockExchangeSystem.Domain.Broker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Brokers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Broker A"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Broker B"
                        });
                });

            modelBuilder.Entity("StockExchangeSystem.Domain.Stock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CurrentPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("TickerSymbol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Stocks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CurrentPrice = 150m,
                            TickerSymbol = "AAPL"
                        },
                        new
                        {
                            Id = 2,
                            CurrentPrice = 250m,
                            TickerSymbol = "MSFT"
                        },
                        new
                        {
                            Id = 3,
                            CurrentPrice = 200m,
                            TickerSymbol = "XOM"
                        },
                        new
                        {
                            Id = 4,
                            CurrentPrice = 90m,
                            TickerSymbol = "GE"
                        },
                        new
                        {
                            Id = 5,
                            CurrentPrice = 500m,
                            TickerSymbol = "GOOGL"
                        },
                        new
                        {
                            Id = 6,
                            CurrentPrice = 320m,
                            TickerSymbol = "TSLA"
                        });
                });

            modelBuilder.Entity("StockExchangeSystem.Domain.Trade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BrokerId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("TEXT");

                    b.Property<int>("StockId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StockId");

                    b.ToTable("Trades");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrokerId = 1,
                            Price = 145m,
                            Quantity = 5m,
                            StockId = 1,
                            Timestamp = new DateTime(2024, 2, 21, 17, 8, 53, 563, DateTimeKind.Utc).AddTicks(5001)
                        },
                        new
                        {
                            Id = 2,
                            BrokerId = 2,
                            Price = 260m,
                            Quantity = 2m,
                            StockId = 2,
                            Timestamp = new DateTime(2024, 2, 22, 17, 8, 53, 563, DateTimeKind.Utc).AddTicks(5038)
                        });
                });

            modelBuilder.Entity("StockExchangeSystem.Domain.Trade", b =>
                {
                    b.HasOne("StockExchangeSystem.Domain.Stock", "Stock")
                        .WithMany()
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stock");
                });
#pragma warning restore 612, 618
        }
    }
}
